name: sealir-tutorial-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        miniconda-version: "latest"
        auto-activate-base: false

    - name: Create conda environment
      run: |
        conda env create --file sealir-tutorials/conda_environment.yml

    - name: Run tests
      working-directory: sealir-tutorials
      run: |
        conda run -n sealir_tutorial pytest tests/ -v